import { pgTable, text, integer, boolean } from 'drizzle-orm/pg-core';

export const companies = pgTable('companies', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  code: text('code').notNull(),
  primaryColor: text('primary_color'),
  secondaryColor: text('secondary_color'),
  logoLightUrl: text('logo_light_url'),
  logoDarkUrl: text('logo_dark_url'),
  showNameNextToLogo: boolean('show_name_next_to_logo').default(false),
  logoHeight: integer('logo_height').default(44),
  logoWidthPct: integer('logo_width_pct').default(85),
  logoAlignment: text('logo_alignment').default('left'),
  logoFit: text('logo_fit').default('contain'),
  designationLine1: text('designation_line_1'),
  designationLine2: text('designation_line_2'),
  designationLine3: text('designation_line_3'),
  departmentsJson: text('departments_json'),
  kpiTargetsJson: text('kpi_targets_json'),
  createdAt: text('created_at'),
});

export const users = pgTable('users', {
  id: text('id').primaryKey(),
  uid: text('uid').unique(),
  email: text('email').notNull(),
  name: text('name').notNull(),
  password: text('password'),
  role: text('role').notNull().default('Administrator'),
  accessScope: text('access_scope').default('Full System'),
  department: text('department').default('Engineering'),
  companyId: text('company_id').references(() => companies.id),
  active: boolean('active').default(true),
  permissionsJson: text('permissions_json'),
  editPermissionsJson: text('edit_permissions_json'),
  deletePermissionsJson: text('delete_permissions_json'),
  signatureName: text('signature_name'),
  signatureTitle: text('signature_title'),
  signatureFont: text('signature_font'),
  signatureColor: text('signature_color'),
  signatureStyle: text('signature_style'),
  signatureImageUrl: text('signature_image_url'),
  profileImageUrl: text('profile_image_url'),
  createdAt: text('created_at'),
});

export const assets = pgTable('assets', {
  uid: text('uid').primaryKey(),
  companyId: text('company_id').references(() => companies.id),
  assetId: text('asset_id').notNull(),
  assetName: text('asset_name').notNull(),
  section: text('section'),
  department: text('department'),
  status: text('status').notNull().default('operational'),
  criticality: text('criticality').notNull().default('A'),
  serialNo: text('serial_no'),
  manufacturer: text('manufacturer'),
  modelNumber: text('model_number'),
  powerRating: text('power_rating'),
  supplier: text('supplier'),
  installationDate: text('installation_date'),
  yearOfManufacture: text('year_of_manufacture'),
  warrantyExpiry: text('warranty_expiry'),
  technicalNotes: text('technical_notes'),
  category: text('category'),
  location: text('location'),
  serviceProvider: text('service_provider'),
  assetValue: text('asset_value'),
  photoUrl: text('photo_url'),
  registeredAt: text('registered_at'),
  createdAt: text('created_at'),
});

export const breakdowns = pgTable('breakdowns', {
  breakdownId: text('breakdown_id').primaryKey(),
  companyId: text('company_id').references(() => companies.id),
  assetUid: text('asset_uid'),
  assetId: text('asset_id').notNull(),
  assetName: text('asset_name').notNull(),
  incidentTitle: text('incident_title').notNull(),
  section: text('section'),
  department: text('department'),
  reportedDt: text('reported_dt').notNull(),
  failureCategory: text('failure_category'),
  severity: text('severity'),
  symptoms: text('symptoms'),
  technicianName: text('technician_name'),
  technicianPhone: text('technician_phone'),
  technicianEmail: text('technician_email'),
  status: text('status').notNull().default('Open'),
  notes: text('notes'),
  durationMins: integer('duration_mins'),
  resolvedAt: text('resolved_at'),
  createdAt: text('created_at'),
});

export const maintenanceTasks = pgTable('maintenance_tasks', {
  taskId: text('task_id').primaryKey(),
  companyId: text('company_id').references(() => companies.id),
  assetUid: text('asset_uid'),
  assetId: text('asset_id').notNull(),
  assetName: text('asset_name').notNull(),
  maintenanceType: text('maintenance_type').notNull(),
  frequency: text('frequency').notNull(),
  section: text('section'),
  technician: text('technician'),
  taskTitle: text('task_title'),
  taskDescription: text('task_description'),
  dueDate: text('due_date').notNull(),
  status: text('status').notNull().default('Scheduled'),
  priority: text('priority').notNull().default('Medium'),
  notes: text('notes'),
  completedAt: text('completed_at'),
  completionNotes: text('completion_notes'),
  createdAt: text('created_at'),
});

export const inventoryParts = pgTable('inventory_parts', {
  uid: text('uid').primaryKey(),
  companyId: text('company_id').references(() => companies.id),
  partName: text('part_name').notNull(),
  sku: text('sku').notNull(),
  category: text('category').notNull(),
  qty: integer('qty').notNull().default(0),
  minQty: integer('min_qty').notNull().default(0),
  storageLocation: text('storage_location'),
  unitPrice: text('unit_price'),
  supplier: text('supplier'),
  leadTimeDays: integer('lead_time_days'),
  isCritical: boolean('is_critical').default(false),
  manufacturer: text('manufacturer'),
  modelNumber: text('model_number'),
  techSpecs: text('tech_specs'),
  photoUrl: text('photo_url'),
  docUrl: text('doc_url'),
  createdAt: text('created_at'),
});

export const recycleBin = pgTable('recycle_bin', {
  id: text('id').primaryKey(),
  companyId: text('company_id'),
  entityType: text('entity_type').notNull(),
  entityLabel: text('entity_label').notNull(),
  primaryId: text('primary_id').notNull(),
  deletedByName: text('deleted_by_name'),
  deletedByEmail: text('deleted_by_email'),
  deletedByRole: text('deleted_by_role'),
  deletedAt: text('deleted_at').notNull(),
  deletedAtIso: text('deleted_at_iso'),
  recordData: text('record_data').notNull(),
  summary: text('summary'),
});

export const technicians = pgTable('technicians', {
  id: text('id').primaryKey(),
  companyId: text('company_id').references(() => companies.id),
  name: text('name').notNull(),
  email: text('email'),
  phone: text('phone'),
  specialization: text('specialization'),
  status: text('status').default('Active'),
  department: text('department'),
  createdAt: text('created_at'),
});

export const auditTrail = pgTable('audit_trail', {
  id: text('id').primaryKey(),
  companyId: text('company_id'),
  action: text('action').notNull(),
  detail: text('detail').notNull(),
  module: text('module').notNull(),
  href: text('href'),
  severity: text('severity').default('info'),
  userName: text('user_name'),
  userEmail: text('user_email'),
  userRole: text('user_role'),
  createdAt: text('created_at'),
});

export const systemSettings = pgTable('system_settings', {
  id: text('id').primaryKey(),
  settingsJson: text('settings_json').notNull(),
  updatedAt: text('updated_at'),
});
