"""init db

Revision ID: 1db66866fc46
Revises: 
Create Date: 2026-02-24 15:46:57.961201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1db66866fc46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('asset_name', sa.String(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('serial_no', sa.String(), nullable=True),
    sa.Column('criticality', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_asset_name'), ['asset_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_section'), ['section'], unique=False)

    op.create_table('inventory_parts',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('part_name', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('compatible_assets', sa.JSON(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('min_qty', sa.Integer(), nullable=True),
    sa.Column('storage_location', sa.String(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('model_number', sa.String(), nullable=True),
    sa.Column('tech_specs', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('doc_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('inventory_parts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_parts_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_parts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_parts_part_name'), ['part_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_parts_sku'), ['sku'], unique=True)

    op.create_table('report_exports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('user_initials', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_size_mb', sa.Float(), nullable=True),
    sa.Column('download_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('send_email', sa.Boolean(), nullable=True),
    sa.Column('schedule_monthly', sa.Boolean(), nullable=True),
    sa.Column('include_cover', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_exports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_exports_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_exports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_exports_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_exports_name'), ['name'], unique=False)

    op.create_table('breakdowns',
    sa.Column('breakdown_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('reported_dt', sa.String(), nullable=True),
    sa.Column('incident_title', sa.String(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('asset_uid', sa.String(), nullable=True),
    sa.Column('asset_name', sa.String(), nullable=True),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('asset_serial_no', sa.String(), nullable=True),
    sa.Column('failure_category', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('symptoms', sa.String(), nullable=True),
    sa.Column('technician_name', sa.String(), nullable=True),
    sa.Column('technician_phone', sa.String(), nullable=True),
    sa.Column('technician_email', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('media', sa.JSON(), nullable=True),
    sa.Column('progress_log', sa.JSON(), nullable=True),
    sa.Column('rca', sa.JSON(), nullable=True),
    sa.Column('duration_mins', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_uid'], ['assets.uid'], ),
    sa.PrimaryKeyConstraint('breakdown_id')
    )
    with op.batch_alter_table('breakdowns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_breakdowns_asset_uid'), ['asset_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_breakdowns_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_breakdowns_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_breakdowns_reported_dt'), ['reported_dt'], unique=False)
        batch_op.create_index(batch_op.f('ix_breakdowns_section'), ['section'], unique=False)
        batch_op.create_index(batch_op.f('ix_breakdowns_status'), ['status'], unique=False)

    op.create_table('maintenance_tasks',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('asset_uid', sa.String(), nullable=True),
    sa.Column('asset_name', sa.String(), nullable=True),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('maintenance_type', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('technician', sa.String(), nullable=True),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('history', sa.JSON(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_uid'], ['assets.uid'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    with op.batch_alter_table('maintenance_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_tasks_asset_uid'), ['asset_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_tasks_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_tasks_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_tasks_section'), ['section'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_tasks_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_maintenance_tasks_section'))
        batch_op.drop_index(batch_op.f('ix_maintenance_tasks_due_date'))
        batch_op.drop_index(batch_op.f('ix_maintenance_tasks_department'))
        batch_op.drop_index(batch_op.f('ix_maintenance_tasks_created_at'))
        batch_op.drop_index(batch_op.f('ix_maintenance_tasks_asset_uid'))

    op.drop_table('maintenance_tasks')
    with op.batch_alter_table('breakdowns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_breakdowns_status'))
        batch_op.drop_index(batch_op.f('ix_breakdowns_section'))
        batch_op.drop_index(batch_op.f('ix_breakdowns_reported_dt'))
        batch_op.drop_index(batch_op.f('ix_breakdowns_department'))
        batch_op.drop_index(batch_op.f('ix_breakdowns_created_at'))
        batch_op.drop_index(batch_op.f('ix_breakdowns_asset_uid'))

    op.drop_table('breakdowns')
    with op.batch_alter_table('report_exports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_exports_name'))
        batch_op.drop_index(batch_op.f('ix_report_exports_department'))
        batch_op.drop_index(batch_op.f('ix_report_exports_created_at'))
        batch_op.drop_index(batch_op.f('ix_report_exports_category'))

    op.drop_table('report_exports')
    with op.batch_alter_table('inventory_parts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_parts_sku'))
        batch_op.drop_index(batch_op.f('ix_inventory_parts_part_name'))
        batch_op.drop_index(batch_op.f('ix_inventory_parts_created_at'))
        batch_op.drop_index(batch_op.f('ix_inventory_parts_category'))

    op.drop_table('inventory_parts')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_section'))
        batch_op.drop_index(batch_op.f('ix_assets_department'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_name'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_id'))

    op.drop_table('assets')
    # ### end Alembic commands ###
