"""enable_breakdowns_db_usage

Revision ID: ff0a729ce704
Revises: 1db66866fc46
Create Date: 2026-02-25 07:32:53.657758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff0a729ce704'
down_revision = '1db66866fc46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_at', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('manufacturer', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('model_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('power_rating', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('supplier', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('installation_date', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('year_of_manufacture', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('warranty_expiry', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('technical_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('service_provider', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('asset_value', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('oem', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status_history', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_assets_registered_at'), ['registered_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_registered_at'))
        batch_op.drop_column('status_history')
        batch_op.drop_column('oem')
        batch_op.drop_column('asset_value')
        batch_op.drop_column('service_provider')
        batch_op.drop_column('location')
        batch_op.drop_column('category')
        batch_op.drop_column('technical_notes')
        batch_op.drop_column('warranty_expiry')
        batch_op.drop_column('year_of_manufacture')
        batch_op.drop_column('installation_date')
        batch_op.drop_column('supplier')
        batch_op.drop_column('power_rating')
        batch_op.drop_column('model_number')
        batch_op.drop_column('manufacturer')
        batch_op.drop_column('registered_at')

    # ### end Alembic commands ###
